# -*- coding: utf-8 -*-
"""Agencia_Viagens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXByR3QA4LPw6cpVkcB55oPyuegar5dA

# Importação de Bibliotecas e Criação de uma tabela de Dados para uma Agência de Viagens

Helder Monteiro , Liliana Gonçalves , Bruna Monteiro , Racia Atanásio

20 de Março 2026
"""

# Verifiquem o PEP 8

import pandas as pd
from datetime import datetime

viagens = pd.DataFrame(columns=[
    "user_id", "origem", "destino", "transporte",
    "custo_transporte", "custo_alojamento", "custo_alimentacao",
    "custo_total", "data_inicio", "data_fim"
])

"""#Lista de Transportes validos possivel adicionar/remover"""

TRANSPORTES_VALIDOS = ["Avião", "Comboio", "Autocarro", "Carro", "Barco", "Bicicleta"]

""" # HU01: Registo de Viagem e adicionar uma nova viagem ao DataFrame com validação de dados."""

def adicionar_viagem(df, viagem_dict):

    if viagem_dict["transporte"] not in TRANSPORTES_VALIDOS:
        raise ValueError(f"Transporte inválido. Escolha entre: {TRANSPORTES_VALIDOS}")

    viagem_dict["custo_total"] = (
        viagem_dict["custo_transporte"] +
        viagem_dict["custo_alojamento"] +
        viagem_dict["custo_alimentacao"]
    )

    inicio_nova = pd.to_datetime(viagem_dict["data_inicio"])
    fim_nova = pd.to_datetime(viagem_dict["data_fim"])

    if fim_nova < inicio_nova:
        raise ValueError("A data de fim não pode ser anterior à data de início.")

    viagens_utilizador = df[df["user_id"] == viagem_dict["user_id"]].copy()
    if not viagens_utilizador.empty:
        viagens_utilizador["data_inicio"] = pd.to_datetime(viagens_utilizador["data_inicio"])
        viagens_utilizador["data_fim"] = pd.to_datetime(viagens_utilizador["data_fim"])

        sobreposicao = viagens_utilizador[
            (inicio_nova <= viagens_utilizador["data_fim"]) &
            (fim_nova >= viagens_utilizador["data_inicio"])
        ]

        if not sobreposicao.empty:
            raise ValueError(f"Erro: O utilizador {viagem_dict['user_id']} já tem uma viagem marcada para este período!")

    return pd.concat([df, pd.DataFrame([viagem_dict])], ignore_index=True)

"""# HU02:Análise de Destinos mais visitados e ordenados"""

def destinos_mais_frequentes(df):
  return df["destino"].value_counts()

"""# HU03: Comparação de custos

total acumulado
"""

def calcular_custo_total(df):
  return df["custo_total"].sum()

"""A função `calcular_custo_total` foi corrigida para somar a coluna `custo_total`:"""

def calcular_custo_total(df):
  return df["custo_total"].sum()

"""A função `custo_medio_por_transporte` foi corrigida para calcular a média da coluna `custo_transporte`:"""

def custo_medio_por_transporte(df):
  return df.groupby("transporte")["custo_transporte"].mean()

"""Custo médio por cada transporte"""

def custo_medio_por_transporte(df):
  return df.groupby("transporte")["custo_transporte"].mean()

"""# Filtro das viagens num intervalo de tempo"""

def filtrar_por_periodo(df, data_inicio, data_fim):
    df_temp = df.copy()
    df_temp["data_inicio"] = pd.to_datetime(df_temp["data_inicio"])

    inicio = pd.to_datetime(data_inicio)
    fim = pd.to_datetime(data_fim)

    return df_temp[(df_temp["data_inicio"] >= inicio) & (df_temp["data_inicio"] <= fim)]

"""#Zona de Teste"""

v1 = {
    "user_id": 3, "origem": "Porto", "destino": "Lisboa", "transporte": "Avião",
    "custo_transporte": 50.0, "custo_alojamento": 100.0, "custo_alimentacao": 60.0,
    "data_inicio": "2026-05-01", "data_fim": "2026-05-10"
}
viagens = adicionar_viagem(viagens, v1)

v2 = {
    "user_id": 3, "origem": "Lisboa", "destino": "Faro", "transporte": "Comboio",
    "custo_transporte": 20.0, "custo_alojamento": 40.0, "custo_alimentacao": 30.0,
    "data_inicio": "2026-05-05", "data_fim": "2026-05-15"
}

try:
    viagens = adicionar_viagem(viagens, v2)
except ValueError as e:
    print(f"Bloqueio de segurança: {e}")

display(viagens)